version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: laravel_php
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel_net
    command: >
      sh -c "
        until mysqladmin ping -hmysql --silent; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done &&
        php artisan migrate --force &&
        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

  redis:
    image: redis:7
    container_name: laravel_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  db_data:
